version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:80"
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db

    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        # volumes:
        #   - postgres_data:/var/lib/postgresql/data
        ports:
            - 1337:5432

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    postgres_data:
