"""Update medical records

Revision ID: 245c35efb2e5
Revises: ffc651771ad5
Create Date: 2024-11-19 17:12:19.048531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '245c35efb2e5'
down_revision: Union[str, None] = 'ffc651771ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medical_records', 'dob',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('medical_records', 'registration_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medical_records', 'insurance_series_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medical_records', 'insurance_company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medical_records', 'social_security_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medical_records', 'identity_document',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records', 'identity_document',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medical_records', 'social_security_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medical_records', 'insurance_company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medical_records', 'insurance_series_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medical_records', 'registration_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medical_records', 'dob',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('medical_records', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
