"""Initial migration

Revision ID: dbaf8f3473f9
Revises: 
Create Date: 2024-10-13 00:27:16.354421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaf8f3473f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.Column('dob', sa.DateTime(), nullable=False),
                    sa.Column('registration_address',
                              sa.String(), nullable=False),
                    sa.Column('insurance_series_number',
                              sa.String(), nullable=False),
                    sa.Column('insurance_company',
                              sa.String(), nullable=False),
                    sa.Column('social_security_number',
                              sa.String(), nullable=False),
                    sa.Column('benefit_code', sa.String(), nullable=True),
                    sa.Column('identity_document',
                              sa.String(), nullable=False),
                    sa.Column('diseases', sa.Text(), nullable=True),
                    sa.Column('icd_code', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_medical_records_id'),
                    'medical_records', ['id'], unique=False)
    op.create_table('patients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('contact_info', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('role', sa.Enum('admin', 'doctor',
                                              'head_doctor', name='userrole'), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('contact_info', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('doctors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('specialty', sa.String(), nullable=False),
                    sa.Column('contact_info', sa.String(), nullable=False),
                    sa.Column('statistics', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('appointments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_time', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_appointments_id'),
                    'appointments', ['id'], unique=False)
    op.create_table('consultations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_time', sa.DateTime(), nullable=False),
                    sa.Column('diagnosis', sa.Text(), nullable=False),
                    sa.Column('patient_review', sa.Text(), nullable=True),
                    sa.Column('treatment', sa.Text(), nullable=True),
                    sa.Column('doctor_notes', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_consultations_id'),
                    'consultations', ['id'], unique=False)
    op.create_table('schedules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('doctor_id', sa.Integer(), nullable=False),
                    sa.Column('date_time', sa.DateTime(), nullable=False),
                    sa.Column('comments', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###
