"""Add FKs

Revision ID: f81279fc0ad7
Revises: dbaf8f3473f9
Create Date: 2024-10-13 00:36:43.642587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81279fc0ad7'
down_revision: Union[str, None] = 'dbaf8f3473f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column(
        'doctor_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column(
        'patient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'patients', [
                          'patient_id'], ['id'])
    op.create_foreign_key(None, 'appointments',
                          'doctors', ['doctor_id'], ['id'])
    op.add_column('consultations', sa.Column(
        'patient_id', sa.Integer(), nullable=False))
    op.add_column('consultations', sa.Column(
        'doctor_id', sa.Integer(), nullable=False))
    op.add_column('consultations', sa.Column(
        'medical_record_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'consultations', 'medical_records', [
                          'medical_record_id'], ['id'])
    op.create_foreign_key(None, 'consultations',
                          'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'consultations',
                          'doctors', ['doctor_id'], ['id'])
    op.add_column('doctors', sa.Column(
        'user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('medical_records', sa.Column(
        'patient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medical_records',
                          'patients', ['patient_id'], ['id'])
    op.add_column('patients', sa.Column(
        'medical_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'medical_records', [
                          'medical_record_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'medical_record_id')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'patient_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'user_id')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'medical_record_id')
    op.drop_column('consultations', 'doctor_id')
    op.drop_column('consultations', 'patient_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'patient_id')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
